# -*- coding: utf-8 -*-
"""Final Presentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvUAV-wIv6jw9WtOj-_LqulsCzFGE62H

# **Analyzing the Factors Influencing Patient Reviews and Healthcare Quality at Saint Luke’s Hospital**

---


---

####**Team Members and  Module Assignment**


*   Ituralde, Josh Andrei A.
> 1. Regression Modelling and Interpretations
> *  Logistic Regression Model & Testing
> * Naive Bayes Model & Testing
> 2. Data Visualization and Statistical Descriptions
>* Roberta Sentiment Distribution
>* Rating Sentiment vs Predicted Sentiment (Confusion Matrix)

*   Kalaw, James Andre L.
> 1. Data Loading and Initial Exploration
> 2. Handling Missing Values
> 3. NLP Procedures and Interpretation of Results
>* Word Cloud

*   Detera, Juliana Ysabel D.C.
> 1. NLP Procedures and Interpretation of Results
> * Pre-processing
> 2. Clustering and Interpretations
> * KMeans
> *Word Cloud Visualization

*   Semilla, Mia Ysabel R.
> 1. Data Visualization and Statistical Descriptions:
> * Distribution of Star Ratings
> * Descriptive Statistics (including 'length')
> * Frequency of Date Commented
> 2. Intrepretations of the Graphs and Charts

*   Villa, Ezra Paul P.
> 1. Data Visualization and Statistical Descriptions
> *  Distribution of Rating Sentiments
> *  Sentiment vs. Review Length
> * Feature Engineering - Review Length

####**Introduction**



> In today's rapidly evolving healthcare landscape, understanding the factors that influence quality assessments is critical for improving patient outcomes. Saint Luke's Hospital serves as a focal point for this exploration, where multiple dimensions—including sentiments, review length, frequency of words, and star ratings—intersect to shape the quality of care. This study aims to identify and analyze these key factors, providing valuable insights that can enhance decision-making and foster continuous improvement in healthcare delivery. Through this research, we seek to contribute to the broader goal of achieving equitable and high-quality healthcare for all patients.

####**Problem Statement**


> This study investigates factors influencing healthcare quality assessments at Saint Luke's Hospital, focusing on sentiments, review length, frequency of words, and star ratings. Understanding these dynamics is essential for improving decision-making processes and enhancing patient outcomes.

####**Objectives**



1.    Identifying Key Themes and Concerns:
> *  Word clouds generated for positive, neutral, and negative reviews visualize prominent themes and concerns. For example, frequent words like "doctor," "care," and "staff" in positive reviews highlight strengths, while "wait," "time," and "billing" in negative reviews indicate areas needing attention. These word clouds directly address the objective of identifying key themes and concerns.

2.  Analyzing Sentiment and Review Characteristics:
> *  Scatter plots and distribution graphs showing the relationship between sentiment and review length provide insights into patient feedback patterns. For instance, if negative sentiment is associated with longer reviews, it suggests that dissatisfied patients provide more detailed explanations. This output helps understand how sentiment influences review characteristics, contributing to the objective.
> * Visualizations or tabular data displaying sentiment trends over time can reveal shifts in patient satisfaction. If negative sentiment increases over a period, it signals a potential decline in patient experience, prompting investigation. This code output supports analyzing sentiment trends, addressing the objective.

3. Evaluating Sentiment Analysis Models:
> * Performance metrics like accuracy, precision, and recall for the Roberta sentiment labels and Logistic Regression/Naive Bayes models are calculated and displayed. Comparing these metrics allows for evaluating the effectiveness of different sentiment analysis approaches. The output directly addresses the objective of evaluating model performance.
> * The confusion matrix provides insights into model misclassifications. For example, if the model frequently misclassifies neutral sentiment as negative, it suggests a need for improvement. Analyzing the confusion matrix aligns with the objective of evaluating model performance.

####****UNSDG and Specific Target****


*   Goal 3: Good Health and Well-Being
*   Target 3.8: Achieve access to quality essential healthcare services.

####**Priorities of the Government**

*   Healthcare Quality Improvement: Aligns with national policies to enhance healthcare services.
*   Evidence-Based Policy Making: Provides data to support effective healthcare policies.
* Technological Integration: Supports initiatives to incorporate innovative solutions in healthcare delivery.

####**Significance of the Study**



> This study aims to analyze the reviews and factors influencing patient feedback at Saint Luke’s Medical Center in Bonifacio Global City (BGC). The focus on the BGC branch stems from the availability of sufficient data, as other branches like Quezon City (QC) and Manila lack substantial feedback. Understanding what drives patient satisfaction and dissatisfaction is vital to improving the hospital’s services and building a stronger reputation. By examining these reviews, the study helps identify strengths and areas for improvement, offering valuable insights for both management and patients.  

> Throughout the term, we applied lessons in Python programming and data analysis to carry out this study. These included foundational concepts like data structures, data manipulation using pandas and NumPy, working with APIs, databases, and creating visualizations. Advanced topics like machine learning and text mining were also utilized to enhance our analysis. The application of these tools allowed for a deeper examination of the data, but there remains room for further explanation and refinement. For example, additional focus could be placed on how specific methods like exploratory data analysis or visualization techniques directly contributed to identifying trends in patient feedback. This opens opportunities for future work to expand and improve the analysis.

---
---



# **Application of DS001 Topics**

1.   **Data Collection and Preprocessing:**
> We load the Saint Luke's Hospital review data using pandas from a CSV file, then check for and handle any missing values. We clean the text reviews by tokenizing, removing stop words, tagging parts of speech, and lemmatizing words to prepare the data for analysis.
2.  **Data Exploration and Visualization:**
> We use descriptive statistics to explore key data characteristics, such as average ratings. We visualize trends in ratings, sentiment, and review lengths through histograms and scatter plots. Word clouds highlight the most frequent words tied to different sentiments, offering insights into the data.
3. **Feature Engineering:**
> We extract features from the reviews using TF-IDF vectorization, converting text into numerical vectors that capture word importance. We also create additional features, like review length, to enrich the dataset for modeling.
4. **Machine Learning Modeling:**
> We apply supervised learning models like Logistic Regression and Naive Bayes to predict sentiment from the reviews. After splitting the data into training and testing sets, we evaluate model performance using accuracy, precision, and recall.
5. **Text Mining:**
> The core of our project involves text mining to extract insights from reviews. We categorize reviews using sentiment analysis (positive, negative, neutral) and analyze word frequencies through word clouds to identify key themes.
6. **Exploratory Data Analysis (EDA):**
> We start with EDA to understand the main characteristics of the data, visualize distributions, explore variable relationships, and identify potential anomalies, setting the stage for deeper analysis.
7. **Natural Language Processing (NLP):**
> We use NLP techniques like tokenization, stop word removal, POS tagging, and lemmatization to prepare the text data. Sentiment analysis, a key NLP application, helps us categorize the reviews.
8. **Supervised Learning:**
> As we predict sentiment from labeled data, we use supervised learning, training our models on data with known outcomes to make accurate predictions.
9. **Data Wrangling/Data Manipulation:**
> We clean, transform, and prepare the data for analysis, including handling missing values, preprocessing text, and engineering features, ensuring the data is ready for modeling.

#Description: The procedures we used for our project.

####**Data and Collection Methods**



*   We collected our Data from Google Reviews.
*   The method we utilized to acquire these datasets is Web scrapping.
*   We made use of Roberta to get the sentiment Distribution.

#Description:

This method is suitable for small files or occasional uploads. For larger files, consider using Google Drive integration.

Once the files are uploaded, they are stored temporarily and will be lost when the Colab session ends. Save any processed data back to your local machine or Google Drive if needed.
"""

from google.colab import files
uploaded = files.upload()

print("To find a certain dataset.")

"""---
---
# **Project:**

**Description**

> This project analyzes patient reviews of St. Luke's Hospital in Bonifacio Global City (BGC) to identify the factors that influence patient satisfaction. The project uses natural language processing (NLP) and machine learning (ML) techniques to process the reviews and identify key themes. The goal of this project is to provide insights that can be used to improve healthcare quality at St. Luke's Hospital.

**Preparation of Dependencies**

> This project uses a variety of libraries to accomplish the tasks. These libraries and their versions are outlined below.



> **Python libraries:**
* pandas (2.0.3)
* numpy (1.25.2)
* seaborn (0.12.2)
* matplotlib (3.7.2)
* nltk (3.8.1)
* wordcloud (1.9.2)
* scikit-learn (1.3.0)

> **NLTK datasets:**
* punkt
* stopwords
* averaged_perceptron_tagger
* wordnet

#Description:
This code snippet is a comprehensive setup for performing text analysis and machine learning tasks.
"""

import pandas as pd               # For data manipulation and analysis
import numpy as np                # For numerical operations and array manipulation
import seaborn as sns             # For creating visually appealing statistical plots
import matplotlib.pyplot as plt   # For creating static, animated, and interactive plots

!pip install nltk                 # Installs the Natural Language Toolkit (NLTK) library
import nltk                       # Imports NLTK for text processing tasks
nltk.download('punkt')            # Downloads the 'punkt' tokenizer model for sentence and word tokenization
nltk.download('punkt_tab')        # Downloads 'punkt_tab' (likely a typo; should be 'punkt')
from nltk.corpus import stopwords # Imports stopwords (common words to ignore in text analysis)
nltk.download('stopwords')        # Downloads the list of stopwords
from nltk.tokenize import word_tokenize # Imports word tokenizer for splitting text into words
nltk.download('averaged_perceptron_tagger_eng') # (Likely a typo; should be 'averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger')    # Downloads the tagger for part-of-speech tagging
nltk.download('wordnet')          # Downloads the WordNet lexical database for lemmatization
from nltk.stem import WordNetLemmatizer # Imports WordNet lemmatizer for reducing words to their base forms
from nltk.corpus import wordnet   # Imports WordNet for lexical relations between words
from sklearn.model_selection import train_test_split # Splits data into training and testing sets
from sklearn.feature_extraction.text import TfidfVectorizer # Converts text to a numerical feature matrix
from sklearn.metrics import accuracy_score, classification_report # For evaluating model performance
!pip install wordcloud            # Installs the WordCloud library for visualizing text data
from wordcloud import WordCloud   # Imports WordCloud for creating word cloud visualizations
from sklearn.metrics import precision_score # For calculating the precision metric
from sklearn.linear_model import LogisticRegression # Imports logistic regression model
from sklearn.metrics import confusion_matrix # For creating a confusion matrix
from sklearn.naive_bayes import MultinomialNB # Imports Naive Bayes classifier for text classification
from sklearn.cluster import KMeans # Clustering and Interpretations (KMeans)

print("To download certain requirements for the task.")

"""#Description:
To load a dataset into memory for analysis and manipulation using the powerful tools provided by the Pandas library.
"""

reviews_df = pd.read_csv(r"St. Luke's BGC Reviews Dataset - St. Luke's BGC Reviews Dataset.csv")

print("Use Panda functions on a dataset.")

"""---
---
# **EDA (Exploratory Data Analysis):**

---
###**1. Data Loading and Initial Exploration:**

#Description:
This is typically used in an interactive Python environment (like Jupyter Notebook, Google Colab, or IPython) to display the contents of the reviews_df DataFrame.
"""

reviews_df

print("To show contents of a dataset.")

"""#Description:
It is an essential tool for understanding the structure and composition of your dataset.
"""

reviews_df.info()

print("Detailed structure of a dataset.")

"""#Description:
To quickly summarize the central tendency, dispersion, and distribution of numeric data in the DataFrame. Useful for understanding the range and characteristics of numeric variables.
"""

reviews_df.describe()

print("Summarization of a dataset in numbers.")

"""> The data shows that most comments were made between 2022 and 2024, with some as early as 2015. The average star rating is 2.6 out of 5, indicating that many reviews were on the lower side. For sentiment, most are neutral or slightly positive, with scores ranging from negative to positive.

---
###**2. Handling Missing Values:**

#Description:
Useful for understanding which data points are incomplete or missing.
"""

# isnull function returns True if there is a missing value

reviews_df.isnull()

print("Showing missing points in a dataset.")

"""#Description:
Makes it easier to quickly identify patterns or clusters of missing data.
"""

#0.0000 means there's no missing value

sns.heatmap(reviews_df.isnull(), yticklabels=False)

print("Display missing data in dataset.")

"""---

###**3. Data Visualization and Statistical Descriptions:**

####**A. Distribution of Star Ratings:**

#Description:
To understand the frequency or count of each star rating (1 to 5) given by users in the dataset.
"""

# Ratings based on the user's chosen rating

plt.figure(figsize=(10, 6))
sns.countplot(x=reviews_df['Star Ratings 1-5'], palette="Set1")

plt.xlabel('Star Ratings (1-5)', fontsize=14, labelpad=10)
plt.ylabel('Count', fontsize=14, labelpad=10)
plt.title('Distribution of Star Ratings', fontsize=16, weight='bold', pad=15)

plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.show()

print("The count of ratings in a dataset.")

"""> The distribution of star ratings shows that most users gave a 1-star rating, followed by a significant number of 5-star ratings. Ratings in the middle (2, 3, and 4 stars) are much less frequent, suggesting polarizing opinions from the users. Another factor also that can be taken into account is that, visitors/ patients consider far difeferent aspects or factors of the said hospital to conclude with their chosen rating.

####**B. Roberta Sentiment Distribution:**

#Description:
To show the frequency of each sentiment classification (likely positive, negative, or neutral) within the dataset.
"""

plt.figure(figsize=(10, 6))
sns.countplot(x=reviews_df['Sentiment'], palette='viridis')

plt.xlabel('Sentiment', fontsize=14, labelpad=10)
plt.ylabel('Count', fontsize=14, labelpad=10)
plt.title('Roberta Sentiment Distribution', fontsize=16, weight='bold', pad=15)

plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.show()

print("The classification of ratings in a dataset.")

"""> This chart shows the distribution of sentiments predicted by the Roberta model, with most classified as negative (label 0), fewer as positive (label 2), and the least as neutral (label 1). Compared to the provided ratings sentiment, which had more neutral entries, it seems to underestimate neutral cases and overfocus on negative ones. This mismatch suggests that it may struggle to identify middle-ground sentiments accurately. Improving the model’s ability to detect neutral sentiments could help align its predictions more closely with the actual ratings sentiment.

####**C. Feature Engineering - Review Length:**

> Feature engineering is the process of selecting, manipulating and transforming raw data into features that can be used in supervised learning. It consists of five processes: feature creation, transformations, feature extraction, exploratory data analysis and benchmarking.

#Description:
To add a new column length that contains the number of characters (or the length) of each review in the Comments column.
"""

reviews_df['length'] = reviews_df['Comments'].apply(len) #Creates a column containing the length of each review
reviews_df['length']

print("Columns wih no. of characters.")

"""#Description:
To show the distribution of the length of reviews, including key summary statistics (quantiles).
"""

# Calculate quantiles
quantiles = reviews_df['length'].quantile([0.25, 0.5, 0.75])

plt.figure(figsize=(10, 6))
reviews_df['length'].plot(bins=100, kind='hist', color='skyblue', edgecolor='blue', alpha=0.8)

# Add vertical lines for quantiles
for quantile, label in zip(quantiles, ['25th Percentile', 'Median', '75th Percentile']):
    plt.axvline(x=quantile, color='red', linestyle='--', linewidth=1.5)
    plt.text(quantile, plt.ylim()[1] * 0.9, label, color='red', fontsize=12, rotation=90, ha='center')

plt.xlabel('Length', fontsize=14, labelpad=10)
plt.ylabel('Frequency', fontsize=14, labelpad=10)
plt.title('Distribution of Review Lengths with Quantiles', fontsize=16, weight='bold', pad=15)

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.tight_layout()
plt.show()

print("Frequency of Reviews.")

"""> The distribution of review lengths shows that most reviews are concentrated around a length of 230, as indicated by the peak near this value. The 25th percentile, median, and 75th percentile also align closely in this range, suggesting that users tend to write moderately long reviews rather than shorter or extremely lengthy ones.

####**D. Sentiment vs. Review Length:**

#Description:
This plot can help to understand whether the sentiment of the review correlates with its length.
"""

plt.figure(figsize=(12, 7))
plt.scatter(
    reviews_df['Sentiment'],
    reviews_df['length'],
    color='skyblue',
    alpha=0.6,
    edgecolor='blue'
)

plt.xlabel('Sentiment', fontsize=14, labelpad=10)
plt.ylabel('Length of Review', fontsize=14, labelpad=10)
plt.title('Sentiment vs. Length of Review', fontsize=16, weight='bold', pad=15)

plt.grid(color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.tight_layout()
plt.show()

print("Relationship between sentiment and review length.")

"""> The scatter plot shows no clear relationship between sentiment and review length, as the points are scattered without any visible pattern. This suggests that the sentiment of a review (positive, neutral, or negative) does not influence how long the review is.

####**E. Descriptive Statistics (including 'length'):**

#Description:
To quickly summarize the central tendency, dispersion, and distribution of numeric data in the DataFrame. Useful for understanding the range and characteristics of numeric variables.
"""

reviews_df.describe()

print("Summarization of a dataset in numbers.")

"""> Review lengths range from 9 to 333 characters, with most clustering around the median of 230 characters. The majority are concise yet meaningful, falling between 141 and 241 characters based on the 25th and 75th percentiles. Longer reviews, like the example praising SLMC-BGC, often share detailed personal experiences.

#Description:
To display the content of the review that has a length of exactly 333 characters.
"""

reviews_df[reviews_df['length'] == 333.000000]['Comments'].iloc[0]

print("Review with the longest length.")

"""> This is an example of it's application; by getting the longest review from the dataset.

####**F. Frequency of Date Commented:**

#Description:
This can help in identifying patterns, such as whether the number of reviews increases or decreases over time.
"""

year_counts = reviews_df['Date Commented'] .value_counts().sort_index()
plt.bar(year_counts.index, year_counts.values, color='skyblue')
plt.xlabel('Year')
plt.ylabel('Frequency')
plt.title('Frequency of Date Commented')
plt.show()

print("The dates' frequency when commented.")

"""> Most of the reviews were posted from 2022 to 2024, likely due to changes brought by the pandemic and the recovery period after it. Starting in 2020, people spent more time online for entertainment, learning, and staying connected, leading to more feedback on online services. These habits continued even after the pandemic, as many adapted to a mix of online and offline activities. This explains the rise in reviews during this period.

####**G. Distribution of Rating Sentiments**

#Description:
This code is used to categorize reviews based on the sentiment implied by their star rating.

*   Ratings of 1 or 2 are interpreted as negative sentiment ('0').
*   A rating of 3 is interpreted as neutral sentiment ('1').
*   Ratings of 4 or 5 are interpreted as positive sentiment ('2').
"""

# This block of code converts the Star Ratings into their respective sentiment
reviews_df['Rating Sentiment'] = np.where(reviews_df['Star Ratings 1-5'].isin([1, 2]), '0',
                                           np.where(reviews_df['Star Ratings 1-5'] == 3, '1',
                                                    np.where(reviews_df['Star Ratings 1-5'].isin([4, 5]), '2', 'Unknown')))
reviews_df['Rating Sentiment']

print("Rating Categories")

"""#Description:
This block of code visualizes the distribution of reviews across different sentiment categories (negative, neutral, positive).
"""

sentiment_counts = reviews_df['Rating Sentiment'].value_counts()

plt.figure(figsize=(10, 7))
plt.style.use('ggplot')

colors = ['#FF6F61', '#FFD700', '#6B8E23']

bars = plt.bar(sentiment_counts.index, sentiment_counts.values, color=colors, alpha=0.9)

plt.xlabel('Sentiment', fontsize=14, labelpad=10)
plt.ylabel('Number of Reviews', fontsize=14, labelpad=10)
plt.title('Distribution of Rating Sentiments', fontsize=16, weight='bold', pad=15)

plt.xticks([0, 1, 2], ['Negative', 'Neutral', 'Positive'], fontsize=12)

plt.grid(axis='y', linestyle='--', alpha=0.7)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 1, f'{height}', ha='center', va='bottom', fontsize=12)
plt.tight_layout()
plt.show()

print("Categorical Rating.")

"""> This graph represents the sentiment based on the user's chosen rating;
*   1 and 2 represents negative
*   3 represents neutral
*   4 and 5 represents positive

####**H. Rating Sentiment vs Predicted Sentiment (Confusion Matrix)**

#Description:
The purpose of this code is to evaluate the performance of the Roberta sentiment model by comparing its predictions (Roberta sentiment) with the actual sentiments derived from the star ratings (Rating sentiment).
"""

reviews_df['Rating Sentiment'] = reviews_df['Rating Sentiment'].astype(int)

cm_svc = confusion_matrix(reviews_df['Rating Sentiment'], reviews_df['Sentiment'])

labels = ['Negative', 'Neutral', 'Positive']
sns.heatmap(cm_svc, annot=True, cmap='Blues', fmt='g', xticklabels=labels, yticklabels=labels)
plt.xlabel('Roberta sentiment')
plt.ylabel('Rating sentiment')
plt.show()

print("Confusion Matrix.")

"""> The Roberta model performs well in predicting negative (120/141) and positive (75/90) sentiments but struggles significantly with neutral ones, correctly identifying only 3 out of 14 cases. Most errors involve misclassifying neutral sentiments as either negative or positive, highlighting a need for improvement in handling middle-ground sentiments.

---
---

# **Processes:**

---
###**1. NLP Procedures and Interpretation of Results**

####**A. Text Preprocessing:**

**I. Tokenization**

> Tokenization is the process of breaking down a piece of text, like a sentence or a paragraph, into individual words or “tokens.”

#Description:
The tokenized comments can be used in later stages of analysis, such as filtering stopwords, stemming, or lemmatization.
"""

reviews_df['tokenized_comments'] = reviews_df['Comments'].apply(word_tokenize)
reviews_df['tokenized_comments']

print("Tokenization")

"""**II. Stop Word Removal**

> Stop words are commonly used words that have very little meaning, such as “a,” “an,” “the,” or “in.” Stopwords are typically excluded from natural language processing (NLP) and information retrieval applications because they do not contribute much to the meaning or context of the text.

#Description:


*   Stopword Removal is a common preprocessing step in NLP to reduce noise in the data.
*   The filtered_comments column now contains only the most meaningful words from each review, which are ready for further processing or analysis.
"""

stop_words = set(stopwords.words('english'))
reviews_df['filtered_comments'] = reviews_df['tokenized_comments'].apply(lambda x: [word for word in x if word.lower() not in stop_words])
reviews_df

print("Analyzing meaning words.")

"""**III. POS Tagging and Lemmatization**

> POS Tagging involves labeling words in a text with their respective parts of speech, such as nouns, verbs, or adjectives, to understand grammatical structure and aid in text analysis. Lemmatization reduces words to their base or dictionary form (lemma) based on context and part of speech, ensuring consistent normalization; for example, "running," "ran," and "runs" are lemmatized to "run." Both techniques are essential in natural language processing for tasks like parsing and text mining.

#Description:
By lemmatizing the words, the analysis focuses on the core meaning of each word, rather than variations of the same word form.
"""

lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}

    return tag_dict.get(tag, wordnet.NOUN)

reviews_df['lemmatized_comments'] = reviews_df['filtered_comments'].apply(lambda x: [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in x])

reviews_df['lemmatized_comments']

print("Lemmatization")

"""> Check if Lemmatization is successful

#Description:
This function checks if the lemmatization process was successful by comparing each word in the original (filtered) comments with its lemmatized counterpart.
"""

def check_lemmatization(row):
    """Check if lemmatization is successful by comparing original and lemmatized words."""
    original_words = row['filtered_comments']
    lemmatized_words = row['lemmatized_comments']

    for i in range(min(len(original_words), len(lemmatized_words))):
        if original_words[i] != lemmatized_words[i]:
            print(f"Original: {original_words[i]}, Lemmatized: {lemmatized_words[i]}")

reviews_df['lemmatized_comments'] = reviews_df['filtered_comments'].apply(lambda x: [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in x])

if 'pos_tags' in reviews_df.columns:
    reviews_df = reviews_df.drop('pos_tags', axis=1)

reviews_df.apply(check_lemmatization, axis=1)

print("diagnossing successful lemmatization.")

"""#### **B. Word cloud Visualization**

#Description:
* Categorize the reviews based on sentiment (positive, neutral, and negative).
* Generate and display word clouds for each sentiment category, providing a visual representation of the most frequent terms in each category.
"""

# This block of code eparates reviews based on sentiment values
negative_reviews = reviews_df[reviews_df['Sentiment'] == 0]['lemmatized_comments']
neutral_reviews = reviews_df[reviews_df['Sentiment'] == 1]['lemmatized_comments'] # Add neutral reviews
positive_reviews = reviews_df[reviews_df['Sentiment'] == 2]['lemmatized_comments']

# This function creates a wordcloud
def create_wordcloud(text_list, title):
  """Creates and displays a word cloud from a list of tokenized text."""
  if len(text_list) == 0:
    print(f"No reviews found for {title}. Skipping word cloud generation.")
    return

  text = ' '.join([' '.join(tokens) for tokens in text_list])
  wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
  plt.figure(figsize=(10, 5))
  plt.imshow(wordcloud, interpolation='bilinear')
  plt.title(title)
  plt.axis('off')
  plt.show()

create_wordcloud(positive_reviews, 'Positive Reviews Word Cloud')
create_wordcloud(neutral_reviews, 'Neutral Reviews Word Cloud') # Add neutral word cloud
create_wordcloud(negative_reviews, 'Negative Reviews Word Cloud')

print("Word Cloud")

"""The positive reviews highlight the hospital's strengths, including its professional staff, cleanliness, high-quality care, and advanced facilities. Words like "doctor," "service," "clean," and "best" emphasize patient satisfaction with the overall healthcare experience. Neutral reviews reflect mixed feedback, often mentioning logistical aspects like "time," "parking," and "insurance." These reviews point to operational inefficiencies, such as long wait times, while still acknowledging the efforts of staff. Negative reviews predominantly focus on delays, financial concerns, and administrative issues, with words like "wait," "slow," "expensive," and "billing" being prominent. Overall, while the hospital excels in care quality and professionalism, addressing wait times, cost transparency, and process efficiency could significantly improve patient satisfaction. These findings align with the objectives of identifying strengths and areas for improvement in patient experiences.

---
###**2. Regression Modelling and Interpretations**

####**A. Feature Preparation:**

#Description:
Converting the text data into numerical form using TF-IDF (Term Frequency-Inverse Document Frequency) vectorization, and setting up the feature matrices for the machine learning model.
"""

x= reviews_df['lemmatized_comments']
y= reviews_df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

X_train = [' '.join(tokens) for tokens in X_train]
X_test = [' '.join(tokens) for tokens in X_test]


vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Feature Preparation")

"""> This script prepares text data for machine learning by splitting and transforming it. The lemmatized comments (x) and corresponding sentiment labels (y) from reviews_df are divided into training and testing sets using train_test_split, with 80% for training. The comments in X_train and X_test are converted into space-joined strings for processing. A TfidfVectorizer is then applied to transform the text data into numerical representations: fit_transform is used on the training data (X_train_tfidf), and transform is used on the testing data (X_test_tfidf), ensuring both datasets are vectorized consistently.

#Description:
 It is likely a pandas DataFrame containing all the data from the original CSV file.
"""

#Overview of the dataset so far
reviews_df

print("full dataset.")

"""####**B.  Logistic Regression Model Training:**

#Description:
This block of code trains a Logistic Regression model on the processed text data, evaluates its performance, and calculates various evaluation metrics.
"""

#Trains the model
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generates a classification report
print(classification_report(y_test, y_pred))

# Calculates precision
precision = precision_score(y_test, y_pred, average='weighted')
print("Precision:", precision)

print("Logistic Regretting Model Training")

""">This script demonstrates the training and evaluation of a Logistic Regression model for text classification. The model is trained using the TF-IDF-transformed training data (X_train_tfidf and y_train) and then predicts sentiment labels for the transformed test data (X_test_tfidf). The performance is evaluated using accuracy_score to measure overall correctness, classification_report for detailed metrics like precision, recall, and F1-score for each class, and precision_score to calculate the weighted precision, which considers the contribution of each class based on its size. The results are printed to assess model performance.

>To further explain and summarize these results, the Logistic Regression model achieved an overall accuracy of 81.63%, which is a strong performance given the threshold of above 80%. The model's precision, recall, and F1-score indicate good performance in classifying the majority class (label 0), but it struggled with underrepresented classes (e.g., label 1, which had no predicted samples). This issue is highlighted by the warnings that precision is ill-defined for labels with no predictions, affecting the macro-average metrics. Despite this, the weighted average metrics show reasonable performance, considering the class imbalance. Overall, the model performs well, but there is room for improvement, especially in handling minority classes.

####**C. Logistic Regression Model Testing:**

#Description:
This block of code defines a function predict_sentiment that uses the trained logistic regression model to predict the sentiment of a given input text.
"""

def predict_sentiment(  text):
  """Predicts the sentiment of a given text using the trained model.

  Args:
    text: The text whose sentiment needs to be predicted.

  Returns:
    The predicted sentiment (e.g., 'Positive', 'Negative', 'Neutral').
  """

  # Preprocess the input text
  tokens = word_tokenize(text)
  filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
  lemmatized_tokens = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in filtered_tokens]
  processed_text = ' '.join(lemmatized_tokens)

  # TransformS the processed text using the trained vectorizer
  text_tfidf = vectorizer.transform([processed_text])

  # MakeS a prediction using the trained model
  prediction = model.predict(text_tfidf)[0]

  return prediction

new_text = input("Mock review: ")
predicted_sentiment = predict_sentiment(new_text)
print(f"Logistic regression predicted sentiment for '{new_text}': {predicted_sentiment}")

print("Sentiment predictions")

"""####**D. Naive Bayes Model Training:**

#Description:
This code trains a Naive Bayes model for sentiment classification and includes a function to predict sentiment using the trained model.
"""

# Trains a Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

# Make predictions on the test set
y_pred_nb = nb_model.predict(X_test_tfidf)

# Evaluate the model
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", accuracy_nb)
print(classification_report(y_test, y_pred_nb))

# Function for predicting sentiment
def predict_sentiment_nb(text):
  """Predicts the sentiment of a given text using the trained Naive Bayes model."""
  # Preprocess the input text (same as before)
  tokens = word_tokenize(text)
  filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
  lemmatized_tokens = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in filtered_tokens]
  processed_text = ' '.join(lemmatized_tokens)

  # Transforms the processed text using the trained vectorizer
  text_tfidf = vectorizer.transform([processed_text])

  # Makes a prediction using the trained Naive Bayes model
  prediction = nb_model.predict(text_tfidf)[0]

  return prediction

  print("Training Model of Naive Bayes")

"""####**E. Naive Bayes Model Testing:**

#Description:
This code allows the user to input a mock review and predicts its sentiment using the previously trained Naive Bayes model.
"""

new_text = input("Mock review: ")
predicted_sentiment_nb = predict_sentiment_nb(new_text)
print(f"Naive Bayes Predicted sentiment for '{new_text}': {predicted_sentiment_nb}")

print("Sentiment Predictions")

"""####**F. Comparing Models:**

#Description:
This code evaluates and compares the performance of the Logistic Regression and Naive Bayes models based on their accuracy and detailed classification metrics.
"""

print("Logistic Regression Accuracy:", accuracy)
print("Naive Bayes Accuracy:", accuracy_nb)


print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, y_pred))

print("\nNaive Bayes Classification Report:")
print(classification_report(y_test, y_pred_nb))

print("Model Compare and Contrast.")

"""---
###**3. Clustering and Interpretations**

####**A. KMeans Clustering**

#Description:
These codes perform K-Means clustering on text data, specifically on the TF-IDF features derived from the text reviews, and interprets the results by analyzing the characteristics of the clusters.
"""

# 1. Feature Preparation (Using TF-IDF features from previous steps)
# X_train_tfidf and X_test_tfidf are already available

# 2. Determine optimal number of clusters (using Elbow Method)
wcss = []  # Within-cluster sum of squares
for i in range(1, 5):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_train_tfidf)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 5), wcss)
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

print("Cluster Optimal Number")

# 3. Apply KMeans with the optimal number of clusters

num_clusters = 2  # Based on Elbow Method visualization
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
clusters = kmeans.fit_predict(X_train_tfidf)

print("KMeans Clustering")

# 4. Add cluster labels to the dataframe

reviews_df['cluster'] = np.nan

X_train_index = X_train.index if isinstance(X_train, pd.DataFrame) else list(range(len(X_train)))
reviews_df.loc[reviews_df.index.isin(X_train_index), 'cluster'] = clusters

print("Assigning Cluster")

# 5. Analyze and Interpret Clusters

# a. Explore cluster characteristics (e.g., using word clouds)
for i in range(num_clusters):
    cluster_reviews = reviews_df[reviews_df['cluster'] == i]['lemmatized_comments']
    create_wordcloud(cluster_reviews, f'Cluster {i} Word Cloud')

print("Characteristic Clusters")

# b. Examine cluster centroids

centroids = kmeans.cluster_centers_
feature_names = vectorizer.get_feature_names_out()

for i in range(num_clusters):
    print(f"Cluster {i}:")
    # Sort centroids by feature importance and get top 10 words
    top_words_indices = centroids[i].argsort()[-10:]
    top_words = [feature_names[j] for j in top_words_indices]
    print(top_words)
    print("\n")

print("Centroid Cluster")

"""####**B. Cluster Interpretation:**

* **Cluster 0:**
>Based on the prominent words ("medical," "beautiful," "go," "service," "patient," "emergency," "call," "test," "get," "time"), this cluster seems to center around reviews related to medical services, emergency care, and patient interactions. The inclusion of "beautiful" suggests some mentions of positive impressions, possibly about the hospital's environment or aesthetics. However, the overall focus appears to be on functional aspects such as tests, emergencies, and service delivery timelines. Sentiment analysis within this cluster could uncover whether patients express satisfaction or concerns with these specific aspects of care.

* Cluster 1:
>The key words in this cluster ("make," "come," "good," "hour," "staff," "service," "best," "wait," "doctor," "hospital") indicate that it represents reviews describing the overall hospital experience. It encompasses evaluations of staff performance, waiting times, and service quality. Words like "good" and "best" point to positive sentiments, while "wait" and "hour" suggest potential concerns about delays. Sentiment analysis would provide further clarity on whether the feedback leans more toward satisfaction or dissatisfaction with these experiences.

#####**Overall Insights:**
>The two clusters reveal distinct aspects of patient feedback on hospital experiences. Cluster 0 focuses on functional and operational elements of care, including emergency services, medical testing, and service timelines. This suggests that patients are primarily reflecting on their interactions with the core processes of care delivery. While positive impressions are hinted at by words like "beautiful," the emphasis lies on efficiency and promptness, making it critical to assess whether patients’ needs are being met effectively. On the other hand, Cluster 1 centers around the broader hospital experience, such as staff interactions, waiting times, and overall service quality. The presence of positive terms like "good" and "best" alongside mentions of "wait" and "hour" indicates that while patients value certain aspects of their experience, delays remain a notable concern. By analyzing the sentiments across both clusters, hospitals can pinpoint strengths and areas needing improvement. Enhancing efficiency in care delivery and reducing delays, while maintaining positive staff engagement, can significantly improve patient satisfaction and build trust.

---
---

#**Summary**

#Description: The synopsis of our project.

>This project analyzed patient reviews from Saint Luke's Hospital in Bonifacio Global City (BGC) to identify the factors influencing healthcare quality assessments. By applying natural language processing (NLP) and machine learning (ML) techniques, we examined a wide range of patient feedback, focusing on sentiment, review length, frequency of words, and star ratings. Key findings from the analysis revealed the following:

* **Key Themes**: Word clouds for positive, neutral, and negative reviews highlighted different patient concerns. Positive reviews praised the hospital's staff, doctors, and facilities, while negative reviews mainly focused on wait times, billing issues, and inefficiencies. Neutral reviews reflected a balance of both satisfaction and areas for improvement.
* **Sentiment Analysis**: The sentiment distribution indicated a tendency towards negative feedback, with the model struggling to detect neutral sentiments. Additionally, sentiment was not closely correlated with review length, suggesting that the depth of feedback doesn't necessarily indicate the overall sentiment.
* **Star Ratings & Review Length**: A polarizing pattern emerged in star ratings, with patients predominantly giving either 1-star or 5-star ratings, indicating extreme experiences. Review lengths were mostly moderate, with most reviews clustering around 230 characters, suggesting that patients generally provide detailed feedback when expressing their opinions.
* **Clustering & Model Evaluation**: K-Means clustering provided insights into specific patient experiences, such as the need for improvements in service efficiency and wait times. Sentiment analysis models (Roberta, Logistic Regression, and Naive Bayes) offered valuable insights but struggled with identifying neutral sentiments and addressing sentiment imbalances in the data.

#**Conclusion**

#Description: The diagnosis of our project.

**Key Findings on Patient Feedback**


*   Positive reviews highlighted strengths like staff professionalism, doctors' expertise, and quality facilities.
*   Negative reviews pointed to issues with wait times, billing practices, and inefficiencies in service.

**Sentiment and Review Patterns**

* Feedback showed a disproportionate tilt toward negative sentiment, with neutral reviews underrepresented.
* Polarization in star ratings (mostly 1-star or 5-star) indicated variability in patient experiences.

**Model Performance and Limitations**

* Sentiment analysis models provided valuable insights but struggled to classify neutral sentiments accurately.
* Refining models and addressing imbalances in sentiment data are needed to improve analysis.

**Recommendations**

* Focus on improving service efficiency and consistency to address patient concerns.
* Refine sentiment analysis models to better capture nuanced feedback, particularly neutral sentiments.
"""